version: "3"
services:
  graphdb:
    container_name: graphdb-preload
    image: ontotext/graphdb:10.3.2
    mem_limit: 250g
    mem_reservation: 250g

    entrypoint: [ "/opt/graphdb/dist/bin/importrdf", "preload", "--chunk", "20m", "--force", "--recursive", "--parsing-tasks", "24", "--recovery-point-interval", "3600", "--id", "metaphactory", "/opt/graphdb/graphdb-import/" ]

    environment:
      GDB_JAVA_OPTS: >-
        -Xms100g
        -Xmx100g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.license.file=/etc/graphdb-license
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/graphdb-import
    volumes:
      - ./graphdb-home:/opt/graphdb/home
      - ./graphdb-import:/opt/graphdb/graphdb-import
      - ./graphdb-license/graphdb.license:/etc/graphdb-license
